# SciKit Learn Preprocessing Overview

In [ ]:
!pip install scikit-learn

In [22]:
import numpy as np

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
data = np.random.randint(0,100,(10,2))

In [25]:
data

array([[85, 77],
       [49, 74],
       [82, 42],
       [ 6, 48],
       [68, 10],
       [85, 77],
       [56, 42],
       [75,  6],
       [76, 73],
       [ 2, 98]])

In [29]:
scaler_model = MinMaxScaler()

In [30]:
scaler_model.fit(data)

MinMaxScaler()

In [31]:
scaler_model.transform(data)

array([[1.        , 0.77173913],
       [0.56626506, 0.73913043],
       [0.96385542, 0.39130435],
       [0.04819277, 0.45652174],
       [0.79518072, 0.04347826],
       [1.        , 0.77173913],
       [0.65060241, 0.39130435],
       [0.87951807, 0.        ],
       [0.89156627, 0.72826087],
       [0.        , 1.        ]])

In [32]:
# In one step
result = scaler_model.fit_transform(data)

In [33]:
result

array([[1.        , 0.77173913],
       [0.56626506, 0.73913043],
       [0.96385542, 0.39130435],
       [0.04819277, 0.45652174],
       [0.79518072, 0.04347826],
       [1.        , 0.77173913],
       [0.65060241, 0.39130435],
       [0.87951807, 0.        ],
       [0.89156627, 0.72826087],
       [0.        , 1.        ]])

In [34]:
import pandas as pd

In [35]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [36]:
data.head()

f1  f2  f3  label
0  31  70  36      5
1  47  15  52     86
2   5  30   3     82
3  84  12  44     71
4  83  79  37     36

In [44]:
data.shape

(50, 4)

In [45]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [48]:
X_train.shape

(35, 3)

In [41]:
X_test.shape

(15, 3)

In [42]:
y_train.shape

(35,)

In [43]:
y_test.shape

(15,)

In [21]:
X_train

f1  f2   f3
3    82  48   79
41   62   0    8
30   27  81   89
15   60  49   24
20   91  88   34
43   90  24   28
38   64  24   16
44    6  42   44
39    4  17    5
10   80  93   70
49   28  98  100
25   77  29   70
33  100  37   98
36   17  50   11
2    95  40   63
27   33  54   26
34   39  17   20
35  100   5   61
8    49  81   96
19   38  57   29
29   29  24   23
12   80  16   19
5    89  40   31
0    59  41   96
28   84  60   88
4    75  79   44
40   87   6   39
13   82  99   93
9    97  81   48
48   69  81   89
23   16  29   12
6    19  18   25
17   51  91    5
11   69  91   13
31   24  78    9