# NumPy

NumPy to potężna biblioteka algebry liniowej dla Pythona. Jej znaczenie wynika z tego, że niemal wszystkie biblioteki w ekosystemie <a href='https://pydata.org/'>PyData</a> (pandas, scipy, scikit-learn itd.) opierają się na NumPy jako jednym z głównych bloków konstrukcyjnych. Dodatkowo będziemy jej używać do generowania danych dla przykładów analiz w kolejnych lekcjach!

NumPy jest również niezwykle szybkie, ponieważ korzysta z powiązań z bibliotekami C. Jeśli chcesz dowiedzieć się, dlaczego warto używać tablic zamiast list, zajrzyj do świetnego [wątku na StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Poznamy jedynie podstawy NumPy. Żeby zacząć, musimy ją zainstalować!

## Instrukcja instalacji

### NumPy jest już częścią Twojego środowiska! Jeśli korzystasz z środowiska kursowego, wszystko jest gotowe!

_____
##### Dla osób, które nie używają przygotowanego środowiska:

**Zdecydowanie zalecamy instalację Pythona poprzez dystrybucję Anaconda, aby wszystkie zależności (np. biblioteki algebry liniowej) poprawnie współpracowały z instalacją conda. Jeśli masz Anacondę, zainstaluj NumPy w terminalu lub wierszu poleceń poleceniem:**
    
    conda install numpy

    pip install numpy
    
**Jeśli nie masz Anacondy i nie możesz jej zainstalować, zajrzyj do [oficjalnej dokumentacji NumPy opisującej różne sposoby instalacji.](https://www.scipy.org/install.html)**

_____


In [3]:
!ls

00-NumPy-Arrays.ipynb                 04-NumPy-Exercises-Solutions.ipynb
01-NumPy-Indexing-and-Selection.ipynb axis_logic.png
02-NumPy-Operations.ipynb             jupyter_lab.ipynb
03-NumPy-Exercises.ipynb              numpy_indexing.png


## Korzystanie z NumPy

Po zainstalowaniu NumPy możesz zaimportować ją jako bibliotekę:

In [4]:
import numpy as np

NumPy ma mnóstwo wbudowanych funkcji i możliwości. Nie omówimy ich wszystkich, zamiast tego skupimy się na najważniejszych aspektach NumPy: wektorach, tablicach, macierzach i generowaniu liczb. Zacznijmy od tablic.

# Tablice NumPy

Tablice NumPy to podstawowy sposób korzystania z NumPy w tym kursie. Występują one w dwóch odmianach: wektory i macierze. Wektory są jednoelementowe wymiarowo (1D), a macierze są dwuwymiarowe (choć nadal mogą mieć tylko jeden wiersz lub jedną kolumnę).

Rozpocznijmy wprowadzenie od pokazania, jak tworzyć tablice NumPy.

## Tworzenie tablic NumPy

### Z listy Pythona

Tablicę możemy utworzyć, bezpośrednio konwertując listę lub listę list:

In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Wbudowane metody

Istnieje wiele wbudowanych sposobów generowania tablic.

### arange

Zwraca równomiernie rozmieszczone wartości w zadanym przedziale. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros i ones

Generują tablice składające się z zer lub jedynek. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Zwraca równomiernie rozmieszczone liczby w podanym przedziale. [[odniesienie](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Zwróć uwagę, że `.linspace()` *uwzględnia* wartość końcową. Aby otrzymać tablicę popularnych ułamków, zwiększ liczbę elementów:</font>

In [17]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Tworzy macierz jednostkową. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Losowe wartości 
NumPy oferuje wiele sposobów tworzenia tablic liczb losowych:

### rand
Tworzy tablicę o zadanym kształcie i wypełnia ją próbkami z rozkładu jednostajnego na przedziale ``[0, 1)``. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [19]:
np.random.rand(2)

array([0.17284386, 0.0691895 ])

In [21]:
np.random.rand(5,5)

array([[0.71537397, 0.4634783 , 0.44832717, 0.45294818, 0.88611146],
       [0.31678403, 0.485146  , 0.94442257, 0.26759753, 0.43320874],
       [0.91231185, 0.03067874, 0.06069942, 0.8508433 , 0.56005774],
       [0.57487686, 0.91317475, 0.89627388, 0.3124483 , 0.44235493],
       [0.4968622 , 0.20957235, 0.30129057, 0.89514115, 0.47627548]])

### randn

Zwraca próbkę (lub próbki) z "standardowego rozkładu normalnego" [σ = 1]. W przeciwieństwie do **rand**, który jest jednostajny, tutaj częściej pojawiają się wartości bliskie zeru. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [22]:
np.random.randn(2)

array([0.96554106, 1.85622855])

In [23]:
np.random.randn(5,5)

array([[-0.90968927, -0.5389371 ,  0.14770353,  0.12492374, -2.42357595],
       [ 1.18327274, -0.69582884,  0.98314476,  0.95479623, -0.39337567],
       [-1.45492123, -0.98905246, -2.93160363,  0.87162462, -1.15532111],
       [ 0.35924672,  0.26149628, -0.56384176,  0.86775127,  1.16039055],
       [ 0.98080534,  1.07661956,  1.43303388,  0.70708595, -0.11791515]])

### randint
Zwraca losowe liczby całkowite z przedziału od `low` (włącznie) do `high` (wyłącznie).  [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [24]:
np.random.randint(1,100)

10

In [25]:
np.random.randint(1,100,10)

array([86, 15, 92, 29, 62, 90, 83, 70, 86, 36])

### seed
Służy do ustawienia stanu generatora losowego, aby można było odtworzyć te same "losowe" wyniki. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [28]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [29]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Atrybuty i metody tablic

Omówmy kilka przydatnych atrybutów i metod tablic.

In [33]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

## Reshape
Zwraca tablicę zawierającą te same dane, ale w nowym kształcie. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

To przydatne metody wyszukiwania wartości maksymalnych lub minimalnych oraz odpowiadających im indeksów dzięki argmax lub argmin.

In [37]:
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

In [38]:
ranarr.max()

np.int64(43)

In [39]:
ranarr.argmax()

np.int64(3)

In [40]:
ranarr.min()

np.int64(1)

In [41]:
ranarr.argmin()

np.int64(1)

## Shape

Shape to atrybut tablic (a nie metoda).  [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [42]:
# Vector
arr.shape

(25,)

In [44]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [45]:
arr.reshape(1,25).shape

(1, 25)

In [46]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [47]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Możesz również sprawdzić typ danych obiektów w tablicy: [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [48]:
arr.dtype

dtype('int64')

In [49]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# Świetna robota!