# NumPy

NumPy to potężna biblioteka algebry liniowej dla Pythona. Jej znaczenie wynika z tego, że niemal wszystkie biblioteki w ekosystemie <a href='https://pydata.org/'>PyData</a> (pandas, scipy, scikit-learn itd.) opierają się na NumPy jako jednym z głównych bloków konstrukcyjnych. Dodatkowo będziemy jej używać do generowania danych dla przykładów analiz w kolejnych lekcjach!

NumPy jest również niezwykle szybkie, ponieważ korzysta z powiązań z bibliotekami C. Jeśli chcesz dowiedzieć się, dlaczego warto używać tablic zamiast list, zajrzyj do świetnego [wątku na StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Poznamy jedynie podstawy NumPy. Żeby zacząć, musimy ją zainstalować!

## Instrukcja instalacji

### NumPy jest już częścią Twojego środowiska! Jeśli korzystasz z środowiska kursowego, wszystko jest gotowe!

_____
##### Dla osób, które nie używają przygotowanego środowiska:

**Zdecydowanie zalecamy instalację Pythona poprzez dystrybucję Anaconda, aby wszystkie zależności (np. biblioteki algebry liniowej) poprawnie współpracowały z instalacją conda. Jeśli masz Anacondę, zainstaluj NumPy w terminalu lub wierszu poleceń poleceniem:**
    
    conda install numpy
    
**Jeśli nie masz Anacondy i nie możesz jej zainstalować, zajrzyj do [oficjalnej dokumentacji NumPy opisującej różne sposoby instalacji.](https://www.scipy.org/install.html)**

_____


## Korzystanie z NumPy

Po zainstalowaniu NumPy możesz zaimportować ją jako bibliotekę:

In [1]:
import numpy as np

NumPy ma mnóstwo wbudowanych funkcji i możliwości. Nie omówimy ich wszystkich, zamiast tego skupimy się na najważniejszych aspektach NumPy: wektorach, tablicach, macierzach i generowaniu liczb. Zacznijmy od tablic.

# Tablice NumPy

Tablice NumPy to podstawowy sposób korzystania z NumPy w tym kursie. Występują one w dwóch odmianach: wektory i macierze. Wektory są jednoelementowe wymiarowo (1D), a macierze są dwuwymiarowe (choć nadal mogą mieć tylko jeden wiersz lub jedną kolumnę).

Rozpocznijmy wprowadzenie od pokazania, jak tworzyć tablice NumPy.

## Tworzenie tablic NumPy

### Z listy Pythona

Tablicę możemy utworzyć, bezpośrednio konwertując listę lub listę list:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Wbudowane metody

Istnieje wiele wbudowanych sposobów generowania tablic.

### arange

Zwraca równomiernie rozmieszczone wartości w zadanym przedziale. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros i ones

Generują tablice składające się z zer lub jedynek. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Zwraca równomiernie rozmieszczone liczby w podanym przedziale. [[odniesienie](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Zwróć uwagę, że `.linspace()` *uwzględnia* wartość końcową. Aby otrzymać tablicę popularnych ułamków, zwiększ liczbę elementów:</font>

In [14]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Tworzy macierz jednostkową. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Losowe wartości 
NumPy oferuje wiele sposobów tworzenia tablic liczb losowych:

### rand
Tworzy tablicę o zadanym kształcie i wypełnia ją próbkami z rozkładu jednostajnego na przedziale ``[0, 1)``. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [16]:
np.random.rand(2)

array([0.37065108, 0.89813878])

In [17]:
np.random.rand(5,5)

array([[0.03932992, 0.80719137, 0.50145497, 0.68816102, 0.1216304 ],
       [0.44966851, 0.92572848, 0.70802042, 0.10461719, 0.53768331],
       [0.12201904, 0.5940684 , 0.89979774, 0.3424078 , 0.77421593],
       [0.53191409, 0.0112285 , 0.3989947 , 0.8946967 , 0.2497392 ],
       [0.5814085 , 0.37563686, 0.15266028, 0.42948309, 0.26434141]])

### randn

Zwraca próbkę (lub próbki) z "standardowego rozkładu normalnego" [σ = 1]. W przeciwieństwie do **rand**, który jest jednostajny, tutaj częściej pojawiają się wartości bliskie zeru. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [18]:
np.random.randn(2)

array([-0.36633217, -1.40298731])

In [19]:
np.random.randn(5,5)

array([[-0.45241033,  1.07491082,  1.95698188,  0.40660223, -1.50445807],
       [ 0.31434506, -2.16912609, -0.51237235,  0.78663583, -0.61824678],
       [-0.17569928, -2.39139828,  0.30905559,  0.1616695 ,  0.33783857],
       [-0.2206597 , -0.05768918,  0.74882883, -1.01241629, -1.81729966],
       [-0.74891671,  0.88934796,  1.32275912, -0.71605188,  0.0450718 ]])

### randint
Zwraca losowe liczby całkowite z przedziału od `low` (włącznie) do `high` (wyłącznie).  [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [20]:
np.random.randint(1,100)

61

In [21]:
np.random.randint(1,100,10)

array([39, 50, 72, 18, 27, 59, 15, 97, 11, 14])

### seed
Służy do ustawienia stanu generatora losowego, aby można było odtworzyć te same "losowe" wyniki. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [22]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [23]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Atrybuty i metody tablic

Omówmy kilka przydatnych atrybutów i metod tablic.

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Zwraca tablicę zawierającą te same dane, ale w nowym kształcie. [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

To przydatne metody wyszukiwania wartości maksymalnych lub minimalnych oraz odpowiadających im indeksów dzięki argmax lub argmin.

In [28]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [29]:
ranarr.max()

39

In [30]:
ranarr.argmax()

7

In [31]:
ranarr.min()

2

In [32]:
ranarr.argmin()

9

## Shape

Shape to atrybut tablic (a nie metoda).  [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [33]:
# Vector
arr.shape

(25,)

In [34]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)

In [36]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [37]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Możesz również sprawdzić typ danych obiektów w tablicy: [[odniesienie](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [38]:
arr.dtype

dtype('int32')

In [39]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# Świetna robota!