# Ćwiczenia z NumPy

Skoro poznaliśmy już NumPy, sprawdźmy Twoją wiedzę. Zaczniemy od kilku prostych zadań, a następnie przejdziemy do trudniejszych pytań.

<div class="alert alert-danger" style="margin: 10px"><strong>WAŻNA UWAGA!</strong> Nie uruchamiaj komórek znajdujących się bezpośrednio nad pokazanym przykładowym wynikiem, <br>bo nadpiszesz wyświetlane rozwiązanie!</div>

#### 1. Zaimportuj NumPy jako np

#### 2. Utwórz tablicę z 10 zer

In [ ]:
# CODE HERE


In [2]:
# DON'T WRITE HERE

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Utwórz tablicę z 10 jedynek

In [3]:
# DON'T WRITE HERE

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Utwórz tablicę z 10 piątek

In [4]:
# DON'T WRITE HERE

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Utwórz tablicę liczb całkowitych od 10 do 50

In [5]:
# DON'T WRITE HERE

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Utwórz tablicę wszystkich liczb parzystych od 10 do 50

In [6]:
# DON'T WRITE HERE

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Utwórz macierz 3x3 z wartościami od 0 do 8

In [7]:
# DON'T WRITE HERE

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Utwórz macierz jednostkową 3x3

In [8]:
# DON'T WRITE HERE

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Użyj NumPy do wygenerowania losowej liczby z przedziału od 0 do 1<br><br>&emsp;UWAGA: Twoja wartość powinna różnić się od tej pokazanej poniżej.

In [9]:
# DON'T WRITE HERE

array([0.65248055])

#### 10. Użyj NumPy do wygenerowania tablicy 25 liczb losowych z rozkładu standardowego normalnego<br><br>&emsp;&ensp;UWAGA: Twoje wartości powinny różnić się od tych pokazanych poniżej.

In [10]:
# DON'T WRITE HERE

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Utwórz następującą macierz:

In [11]:
# DON'T WRITE HERE

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Utwórz tablicę 20 punktów liniowo rozmieszczonych między 0 a 1:

In [12]:
# DON'T WRITE HERE

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indeksowanie i wybór w NumPy

Poniżej otrzymasz macierz startową (koniecznie uruchom następną komórkę!) oraz zadanie odtworzenia przedstawionych wyników:

In [13]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Napisz kod odtwarzający wynik pokazany poniżej.<br><br>&emsp;&ensp;Uważaj, aby nie uruchomić komórki bezpośrednio nad wynikiem, bo nie zobaczysz już przykładowego wyjścia.

In [ ]:
# CODE HERE


In [14]:
# DON'T WRITE HERE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Napisz kod odtwarzający wynik pokazany poniżej.

In [15]:
# DON'T WRITE HERE

20

#### 15. Napisz kod odtwarzający wynik pokazany poniżej.

In [16]:
# DON'T WRITE HERE

array([[ 2],
       [ 7],
       [12]])

#### 16. Napisz kod odtwarzający wynik pokazany poniżej.

In [17]:
# DON'T WRITE HERE

array([21, 22, 23, 24, 25])

#### 17. Napisz kod odtwarzający wynik pokazany poniżej.

In [18]:
# DON'T WRITE HERE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Operacje NumPy

#### 18. Oblicz sumę wszystkich wartości w macierzy mat

In [19]:
# DON'T WRITE HERE

325

#### 19. Wyznacz odchylenie standardowe wartości w macierzy mat

In [20]:
# DON'T WRITE HERE

7.211102550927978

#### 20. Oblicz sumy wszystkich kolumn w macierzy mat

In [21]:
# DON'T WRITE HERE

array([55, 60, 65, 70, 75])

## Pytanie dodatkowe

Dużo pracowaliśmy na losowych danych w NumPy, ale czy istnieje sposób, aby zawsze otrzymywać te same liczby losowe? [Kliknij tutaj po wskazówkę](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

# Świetna robota!